import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getLang } from "@/utils/getLang";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout( {children}: Readonly<{children: React.ReactNode;}>) {
	const { lang, dict } = await getLang();

	return (
		<html lang={lang} suppressHydrationWarning>      
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<ThemeProvider attribute="class" disableTransitionOnChange> 
					<Header />
					{children}
					<Footer />
            	</ThemeProvider>
			</body>
		</html>
	);
}
